"""Added day_expense_limit row in users table

Revision ID: 7b19fd1ed4a4
Revises: 141fbce9ba28
Create Date: 2025-11-08 12:35:02.610039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7b19fd1ed4a4"
down_revision: Union[str, Sequence[str], None] = "141fbce9ba28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM expenses")
    op.execute("DELETE FROM incomes")
    op.execute("DELETE FROM users")
    op.add_column(
        "users",
        sa.Column(
            "day_expense_limit", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###

    op.add_column("expenses", sa.Column("image_key", sa.String(255), nullable=True))
    # Добавляем колонку в таблицу income
    op.add_column("incomes", sa.Column("image_key", sa.String(255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_column("users", "day_expense_limit")
    # ### end Alembic commands ###

    op.drop_column("expenses", "image_key")
    op.drop_column("incomes", "image_key")
