"""Add user roles to user table

Revision ID: b70032e85960
Revises: be97c05fa85a
Create Date: 2026-02-19 18:57:50.574172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b70032e85960"
down_revision: Union[str, Sequence[str], None] = "be97c05fa85a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM incomes")
    op.execute("DELETE FROM expenses")
    op.execute("DELETE FROM categories")
    op.execute("DELETE FROM users")

    op.execute("CREATE TYPE userroles AS ENUM ('USER', 'ADMIN')")

    op.alter_column(
        "expenses",
        "value",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "incomes",
        "value",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="userroles"),
            server_default="USER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.alter_column(
        "incomes",
        "value",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "expenses",
        "value",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
