"""Added user_id to category table ont-to-many

Revision ID: be97c05fa85a
Revises: 7b19fd1ed4a4
Create Date: 2025-11-08 14:35:01.234381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be97c05fa85a"
down_revision: Union[str, Sequence[str], None] = "7b19fd1ed4a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM expenses")
    op.execute("DELETE FROM incomes")
    op.execute("DELETE FROM users")
    op.execute("DELETE FROM categories")

    op.add_column("categories", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "categories", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "user_id")
    # ### end Alembic commands ###
